name: warehouses
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0-133.0.dev

dependencies:
  flutter:
    sdk: flutter
  path_provider_android:

  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0

  uuid: ^4.4.0
  auth0: ^2.2.1

  # firebase_core: ^3.1.0
  # firebase_ui_auth: ^1.15.0
  # firebase_ui_firestore: ^1.6.4
  # firebase_auth: ^5.1.0
  # firebase_storage: ^12.0.1
  # cloud_firestore: ^5.0.1
  go_router: ^14.2.0
  equatable: ^2.0.5
  internet_connection_checker_plus: ^2.5.0
  # mongo_dart: ^0.10.3
  collection: ^1.18.0
  crypto: ^3.0.6
  supabase_flutter: ^2.6.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
